export const kdCompanys = [
  { name: '圆通速递', code: 'yuantong', type: 1 },
  { name: '中通快递', code: 'zhongtong', type: 1 },
  { name: '韵达快递', code: 'yunda', type: 1 },
  { name: '顺丰速运', code: 'shunfeng', type: 2 },
  { name: '申通快递', code: 'shentong', type: 1 },
  { name: '极兔速递', code: 'jtexpress', type: 1 },
  { name: '邮政快递包裹', code: 'youzhengguonei', type: 2 },
  { name: '京东物流', code: 'jd', type: 1 },
  { name: 'EMS', code: 'ems', type: 2 },
  { name: '德邦快递', code: 'debangkuaidi', type: 1 },
  { name: '邮政电商标快', code: 'youzhengdsbk', type: 1 },
  { name: '邮政标准快递', code: 'youzhengbk', type: 1 },
  { name: '菜鸟速递', code: 'danniao', type: 1 },
  { name: '中通快运', code: 'zhongtongkuaiyun', type: 1 },
  { name: '德邦物流', code: 'debangwuliu', type: 1 },
  { name: '顺丰快运', code: 'shunfengkuaiyun', type: 1 },
  { name: '跨越速运', code: 'kuayue', type: 1 },
  { name: '京东快运', code: 'jingdongkuaiyun', type: 1 },
  { name: '顺心捷达', code: 'sxjdfreight', type: 1 },
  { name: '安能快运', code: 'annengwuliu', type: 1 },
  { name: '京广速递', code: 'jinguangsudikuaijian', type: 1 },
  { name: 'USPS', code: 'usps', type: 2 },
  { name: '百世快运', code: 'baishiwuliu', type: 1 },
  { name: '安得物流', code: 'annto', type: 1 },
  { name: '韵达快运', code: 'yundakuaiyun', type: 1 },
  { name: '中通国际', code: 'zhongtongguoji', type: 2 },
  { name: '壹米滴答', code: 'yimidida', type: 1 },
  { name: '优速', code: 'youshuwuliu', type: 1 },
  { name: '平安达腾飞', code: 'pingandatengfei', type: 1 },
  { name: '加运美', code: 'jiayunmeiwuliu', type: 1 },
  { name: '日日顺物流', code: 'rrs', type: 1 },
  { name: '速必达', code: 'subida', type: 1 },
  { name: 'EMS物流', code: 'emswuliu', type: 1 },
  { name: 'FedEx-国际件', code: 'fedex', type: 2 },
  { name: '联昊通', code: 'lianhaowuliu', type: 1 },
  { name: '信丰物流', code: 'xinfengwuliu', type: 1 },
  { name: '中铁快运', code: 'ztky', type: 1 },
  { name: 'UPS', code: 'ups', type: 2 },
  { name: 'DHL-中国件', code: 'dhl', type: 2 },
  { name: 'UPS-全球件', code: 'upsen', type: 2 },
  { name: '速腾快递', code: 'suteng', type: 1 },
  { name: '国际包裹', code: 'youzhengguoji', type: 2 },
  { name: '芝麻开门', code: 'zhimakaimen', type: 1 },
  { name: '海信物流', code: 'savor', type: 1 },
  { name: '佰纳博通', code: 'viechina', type: 1 },
  { name: '申通国际', code: 'stosolution', type: 2 },
  { name: '菜鸟大件', code: 'cainiaodajian', type: 1 },
  { name: '百世快递', code: 'huitongkuaidi', type: 1 },
  { name: '宅急送', code: 'zhaijisong', type: 1 },
  { name: '苏宁物流', code: 'suning', type: 1 },
  { name: '中国邮政（CHINA POST）', code: 'chinapost', type: 2 },
  { name: 'EWE全球快递', code: 'ewe', type: 2 },
  { name: '汇森速运', code: 'huisenky', type: 1 },
  { name: 'DHL-全球件', code: 'dhlen', type: 2 },
  { name: 'Fedex-国际件-中文', code: 'fedexcn', type: 2 },
  { name: '递四方', code: 'disifang', type: 1 },
  { name: '宅急便', code: 'zhaijibian', type: 2 },
  { name: '日本（Japan Post）', code: 'japanposten', type: 2 },
  { name: '融辉物流', code: 'ronghui', type: 1 },
  { name: '中通冷链', code: 'ztocc', type: 1 },
  { name: 'DPD Germany', code: 'dpdgermany', type: 2 },
  { name: '全通速递', code: 'quantong56', type: 1 },
  { name: '洋包裹', code: 'yangbaoguo', type: 2 },
  { name: 'Titan泰坦国际速递', code: 'timelytitan', type: 2 },
  { name: '转运四方', code: 'zhuanysifang', type: 2 },
  { name: '明通国际快递', code: 'tnjex', type: 2 },
  { name: '威盛快递', code: 'wherexpess', type: 1 },
  { name: '安能快递', code: 'ane66', type: 1 },
  { name: '百世国际', code: 'baishiguoji', type: 2 },
  { name: '中远e环球', code: 'cosco', type: 2 },
  { name: '圆通国际', code: 'yuantongguoji', type: 2 },
  { name: '笨鸟速运', code: 'benniaosuyun', type: 1 },
  { name: '金大物流', code: 'jindawuliu', type: 1 },
  { name: 'Flextock', code: 'flextock', type: 2 },
  { name: 'EMS包裹', code: 'emsbg', type: 2 },
  { name: '速通物流', code: 'sut56', type: 1 },
  { name: '盛辉物流', code: 'shenghuiwuliu', type: 1 },
  { name: '袋鼠速递', code: 'xjdaishu', type: 1 },
  { name: '顺丰冷链', code: 'shunfenglengyun', type: 1 },
  { name: '源安达', code: 'yuananda', type: 1 },
];

export const kdStates = [
  { code: '1', name: '揽收' },
  { code: '101', name: '已下单' },
  { code: '102', name: '待揽收' },
  { code: '103', name: '已揽收' },
  { code: '0', name: '在途' },
  { code: '1001', name: '到达派件城市' },
  { code: '1002', name: '干线' },
  { code: '1003', name: '转递' },
  { code: '5', name: '派件' },
  { code: '501', name: '投柜或驿站' },
  { code: '3', name: '签收' },
  { code: '301', name: '本人签收' },
  { code: '302', name: '派件异常后签收' },
  { code: '303', name: '代签' },
  { code: '304', name: '投柜或站签收' },
  { code: '6', name: '退回' },
  { code: '4', name: '退签' },
  { code: '401', name: '已销单' },
  { code: '14', name: '拒签' },
  { code: '7', name: '转投' },
  { code: '2', name: '疑难' },
  { code: '201', name: '超时未签收' },
  { code: '202', name: '超时未更新' },
  { code: '203', name: '拒收' },
  { code: '204', name: '派件异常' },
  { code: '205', name: '柜或驿站超时未取' },
  { code: '206', name: '无法联系' },
  { code: '207', name: '超区' },
  { code: '208', name: '滞留' },
  { code: '209', name: '破损' },
  { code: '210', name: '销单' },
  { code: '8', name: '清关' },
  { code: '10', name: '待清关' },
  { code: '11', name: '清关中' },
  { code: '12', name: '已清关' },
  { code: '13', name: '清关异常' },
];

export default {
  getKdCompany(code: string) {
    return kdCompanys.find((it) => it.code == code)?.name || code;
  },
  getKdState(code: string) {
    return kdStates.find((it) => it.code == code)?.name || code;
  },
};
